#!/bin/bash


_hunter_zip () {
    if [[ $GIT_REPO ]]
    then
        echo "https://github.com/${GIT_REPO}/archive/master.zip"
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMtVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}

_library () {
    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then 
        python3 -m PyrogramHunter
    else
        python3 -m TelethonHunter
    fi
}

_starter () {
    local Hunterpath
    Hunterpath="Plugins.zip"
    echo "••• DOWNLOADING HUNTER X  •••"
    wget -q $(_hell_zip) -O "$hellpath"
    HUNTERPATH=$(zipinfo -1 "$hellpath" | grep -v "/.");
    unzip -qq "$hunterpath"
    rm -rf "$hunterpath"
    cd $HUNTERPATH
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING HUNTERX  •••"
    _library
}

_starter
